### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by holopleather**
Modified states.py and Created readme.md 

states.py
* changes within states.py also commented within
* reversed order of if statements (lines 22-26)
* changed miner.fatigue to -= 1 (line 60)
* commented out line 62 as it is no longer needed
* new if statement (line 63 -66)
* line 66 also contains new dialogue
* fixed mistake on line 68 that made the miner go home if they were thirsty
* updated exit dialogue (line 73)
* changed miner.thirst to -= 3
* dialogue on line 85 commented out and moved to line 97
* new dialogue (line 86)
* new if statement (line 87-89)
* new if statement (line 90-92)
* comment (line 96)

### CODE REVIEW

**Comment by jzmiller1** [comment]
What does this commit do?  There's no commit message.  It can't be pulled in until there's a message attached.  We also need to remove your merge commit.

**Comment by holopleather** [comment]
I added the message I don't know what happened with that other thing though.

**Comment by holopleather** [comment]
You know what I'll just try this again.

**Comment by holopleather** [comment]
I only want to submit the second commit, the first I do not even recall creating. But I cannot submit a pull request for the second commit without submitting the first and I cannot find a way to remove the first commit.

**Comment by jzmiller1** [comment]
Can you join the slack group?  We can discuss what to do there.

**Comment by holopleather** [comment]
I have not received an invitation.

**Comment by jzmiller1** [comment]
Check your email

**Comment by holopleather** [comment]
still no invitation

**Comment by jzmiller1** [comment]
Look in clutter

**Comment by holopleather** [comment]
alright, I'm in

**Pull request closed without merging**
